import assert from 'node:assert/strict'
import { mkdtemp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { ISSUER_ORDER, formatRunSummary, orchestrateIngestion, overallHealth } from '../../scripts/ingestion/ingestion-orchestrator.mjs'

const clock=()=>new Date('2026-08-14T12:00:00.000Z')
const success=(created=0,revisions=0,candidateCount=2)=>async()=>({created,revisions,candidateCount,transitions:revisions})
function runners(overrides={}){return Object.fromEntries(ISSUER_ORDER.map((issuer)=>[issuer,overrides[issuer]??success()]))}
const verify=async()=>({hyperscaler:'POSITIVE/HIGH',cross:'POSITIVE/CONFIRMED/HIGH'})
const root=()=>mkdtemp(path.join(os.tmpdir(),'orchestrator-test-'))
async function snapshot(directory){return Promise.all((await readdir(directory)).sort().map(async file=>[file,await readFile(path.join(directory,file),'utf8')]))}
async function run(options={}){return orchestrateIngestion({outputRoot:await root(),issuerRunners:runners(),verificationRunner:verify,now:clock,persistReport:false,...options})}

test('all five succeed in deterministic order and produce HEALTHY',async()=>{const {report,exitCode}=await run();assert.deepEqual(report.issuerResults.map(x=>x.issuer),ISSUER_ORDER);assert.ok(report.issuerResults.every(x=>x.status==='SUCCESS'));assert.equal(report.overallHealth,'HEALTHY');assert.equal(exitCode,0)})
test('one issuer failure produces PARTIAL_FAILURE and non-zero exit',async()=>{const {report,exitCode}=await run({issuerRunners:runners({MSFT:async()=>{throw Object.assign(new Error('bad document'),{code:'WRONG_DOCUMENT'})}})});assert.equal(report.overallHealth,'PARTIAL_FAILURE');assert.equal(report.totals.failures,1);assert.equal(report.issuerResults[2].errorCode,'WRONG_DOCUMENT');assert.equal(exitCode,1)})
test('first issuer failure does not stop later issuers',async()=>{const calls=[];const custom=runners(Object.fromEntries(ISSUER_ORDER.map((issuer)=>[issuer,async()=>{calls.push(issuer);if(issuer==='TSMC')throw Object.assign(new Error('offline'),{code:'SOURCE_UNAVAILABLE'});return{created:0,revisions:0,candidateCount:1}}])));await run({issuerRunners:custom});assert.deepEqual(calls,ISSUER_ORDER)})
test('multiple issuer failures are retained',async()=>{const bad=()=>async()=>{throw Object.assign(new Error('failed'),{code:'SOURCE_UNAVAILABLE'})};const {report}=await run({issuerRunners:runners({META:bad(),AMZN:bad()})});assert.equal(report.totals.failures,2);assert.equal(report.overallHealth,'PARTIAL_FAILURE')})
test('downstream failure after successful ingestion is VERIFICATION_FAILURE',async()=>{const {report,exitCode}=await run({verificationRunner:async()=>{throw Object.assign(new Error('regression'),{code:'SIGNAL_REGRESSION'})}});assert.equal(report.overallHealth,'VERIFICATION_FAILURE');assert.equal(report.verification.errorCode,'SIGNAL_REGRESSION');assert.equal(exitCode,1)})
test('issuer and verification failures preserve both and deterministically choose PARTIAL_FAILURE',async()=>{const {report}=await run({issuerRunners:runners({GOOG:async()=>{throw new Error('bad')}}),verificationRunner:async()=>{throw new Error('also bad')}});assert.equal(report.overallHealth,'PARTIAL_FAILURE');assert.equal(report.verification.status,'FAILED');assert.equal(report.totals.failures,1)})
test('unchanged run reports zero new facts and correct unchanged count',async()=>{const {report}=await run();assert.equal(report.totals.newFacts,0);assert.equal(report.totals.unchanged,10);assert.ok(report.issuerResults.every(x=>!x.canonicalChanged))})
test('new facts aggregate correctly',async()=>{const {report}=await run({issuerRunners:runners({TSMC:success(3,0,5),META:success(2,0,2)})});assert.equal(report.totals.newFacts,5);assert.equal(report.totals.unchanged,8)})
test('revisions aggregate correctly and mark canonical changed',async()=>{const {report}=await run({issuerRunners:runners({MSFT:success(1,1,7),GOOG:success(2,2,7)})});assert.equal(report.totals.revisions,3);assert.ok(report.issuerResults.filter(x=>['MSFT','GOOG'].includes(x.issuer)).every(x=>x.canonicalChanged))})
test('health-state function never reports healthy with issuer failure',()=>{assert.equal(overallHealth([{status:'FAILED'}],{status:'PASSED'}),'PARTIAL_FAILURE');assert.equal(overallHealth([{status:'SUCCESS'}],{status:'FAILED'}),'VERIFICATION_FAILURE')})
test('summary includes deterministic statuses and totals',async()=>{const {report}=await run();const text=formatRunSummary(report);assert.match(text,/TSMC\s+SUCCESS/);assert.match(text,/Overall:\n HEALTHY/);assert.match(text,/New facts\s+0/)})
test("run report serialization is stable and filesystem-safe",async()=>{const outputRoot=await root();const a=await orchestrateIngestion({outputRoot,issuerRunners:runners(),verificationRunner:verify,now:clock});const parsed=JSON.parse(await readFile(a.reportPath,"utf8"));const filename=path.basename(a.reportPath);assert.deepEqual(parsed,a.report);assert.match(a.report.runId,/^ingestion-run:sha256:[a-f0-9]{64}$/);assert.match(filename,/^ingestion-run-[a-f0-9]{64}[.]json$/);assert.equal([...filename].some(char=>[34,58,60,62,124,42,63,13,10].includes(char.charCodeAt(0))),false)})
test("dry run uses a disposable canonical copy and leaves production observations unchanged",async()=>{const outputRoot=await root(),observations=path.join(outputRoot,"observations");await mkdir(observations,{recursive:true});for(const file of ["tsm-monthly.json","meta-annual-capex-guidance.json","msft-management-total-capex.json","goog-annual-capex-guidance.json","amzn-ppe-purchases.json"])await writeFile(path.join(observations,file),"{\"original\":true}\n");const before=await snapshot(observations);const factory=(executionRoot)=>Object.fromEntries(ISSUER_ORDER.map((issuer,index)=>[issuer,async()=>{await writeFile(path.join(executionRoot,"observations",`${index}.json`),"changed");return{created:1,revisions:0,candidateCount:1}}]));const {report}=await orchestrateIngestion({outputRoot,dryRun:true,issuerRunnerFactory:factory,verificationRunner:verify,now:clock,persistReport:false});const after=await snapshot(observations);assert.deepEqual(after,before);assert.equal(report.dryRun,true);assert.equal(report.totals.newFacts,5)})
