import assert from 'node:assert/strict'
import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { classifyMonitoringReport, latestRunReport, renderMonitoringSummary } from '../../scripts/ingestion/monitoring-summary.mjs'

const base={overallHealth:'HEALTHY',issuerResults:['TSMC','META','MSFT','GOOG','AMZN'].map(issuer=>({issuer,status:'SUCCESS'})),totals:{newFacts:0,revisions:0,provenanceReassertions:0,quarantined:0,failures:0},verification:{status:'PASSED'},baselineVerification:{status:'PASSED'},proposedStateVerification:{status:'PASSED'}}
test('monitoring classifications distinguish every operational state',()=>{assert.equal(classifyMonitoringReport(base),'NO CHANGE');assert.equal(classifyMonitoringReport({...base,totals:{...base.totals,provenanceReassertions:6}}),'NO CHANGE');assert.equal(classifyMonitoringReport({...base,totals:{...base.totals,newFacts:1}}),'NEW FACTS DETECTED');assert.equal(classifyMonitoringReport({...base,totals:{...base.totals,newFacts:1,revisions:1}}),'REVISION DETECTED');assert.equal(classifyMonitoringReport({...base,overallHealth:'PARTIAL_FAILURE',totals:{...base.totals,failures:1}}),'INGESTION FAILURE');assert.equal(classifyMonitoringReport({...base,overallHealth:'VERIFICATION_FAILURE',verification:{status:'FAILED'}}),'VERIFICATION FAILURE')})
test('known historical source warning is visible but non-fatal',()=>{const warning={code:'KNOWN_HISTORICAL_SOURCE_UNAVAILABLE'},report={...base,issuerResults:base.issuerResults.map((item)=>item.issuer==='GOOG'?{...item,warnings:[warning]}:item),totals:{...base.totals,warnings:1}};assert.equal(classifyMonitoringReport(report),'KNOWN SOURCE WARNING');const summary=renderMonitoringSummary(report);assert.match(summary,/GOOG \| SUCCESS — KNOWN_HISTORICAL_SOURCE_UNAVAILABLE/);assert.match(summary,/Warnings \| 1/);assert.match(summary,/Overall health:\*\* HEALTHY/)})
test('step summary contains issuer, totals, verification, and dry-run notice',()=>{const summary=renderMonitoringSummary(base);assert.match(summary,/TSMC/);assert.match(summary,/New facts \| 0/);assert.match(summary,/Provenance reassertions \| 0/);assert.match(summary,/Baseline verification:\*\* PASSED/);assert.match(summary,/Proposed-state verification:\*\* PASSED/);assert.match(summary,/dry-run only/)})
test('latest report selection and JSON serialization are deterministic',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'monitor-report-'));await writeFile(path.join(directory,'a.json'),JSON.stringify({...base,runId:'a'}));await new Promise(resolve=>setTimeout(resolve,10));await writeFile(path.join(directory,'b.json'),JSON.stringify({...base,runId:'b'}));const found=await latestRunReport(directory);assert.equal(found.report.runId,'b')})
test('workflow is scheduled/manual, read-only, dry-run only, guarded, and uploads reports',async()=>{const yaml=await readFile('.github/workflows/ingestion-monitor.yml','utf8');assert.match(yaml,/schedule:/);assert.match(yaml,/workflow_dispatch:/);assert.match(yaml,/contents: read/);assert.doesNotMatch(yaml,/contents: write|pull-requests: write/);assert.match(yaml,/npm run ingest:all -- --dry-run/);assert.doesNotMatch(yaml,/run: npm run ingest:all\s*$/m);assert.match(yaml,/git diff --exit-code -- data\/ingestion\/observations/);assert.match(yaml,/if: always\(\)/);assert.match(yaml,/actions\/upload-artifact@v4/);assert.match(yaml,/SEC_USER_AGENT/);assert.match(yaml,/cancel-in-progress: false/)})
