import assert from 'node:assert/strict'
import { mkdtemp } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { IngestionError } from '../../scripts/ingestion/tsm-monthly-lib.mjs'
import { TSMC_SEC_ACQUISITION, discoverTsmcMonthlyFilings, ingestTsmcMonthlyFromSec, parseSecMonthlyRevenue } from '../../scripts/ingestion/tsm-sec-lib.mjs'

const agent='AI Infrastructure Monitor tests maintainer@example.com'
const rows=[
  ['January',2026,'401,255','293,288','36.8','000015','2026-02-10'],
  ['February',2026,'317,657','260,009','22.2','000031','2026-03-10'],
  ['March',2026,'415,191','285,957','45.2','000136','2026-04-10'],
  ['April',2026,'410,726','349,567','17.5','000213','2026-05-08'],
  ['May',2026,'416,975','320,516','30.1','000367','2026-06-10'],
  ['June',2026,'442,680','263,709','67.9','000447','2026-07-13'],
]
function document(month,year,revenue,prior,yoy) { return '<html><body><h1>FORM 6-K</h1><p>Taiwan Semiconductor Manufacturing Company Limited</p><h2>TSMC '+month+' '+year+' Revenue Report</h2><table><tr><th>TSMC '+month+' Revenue Report (Consolidated): (Unit:NT$ million)</th></tr><tr><th>Period</th><th>'+month+' '+year+'</th><th>Prior Month</th><th>M-o-M Increase(Decrease)%</th><th>'+month+' '+(year-1)+'</th><th>Y-o-Y Increase(Decrease)%</th></tr><tr><td>Net Revenue</td><td>'+revenue+'</td><td>300,000</td><td>1.0</td><td>'+prior+'</td><td>'+yoy+'</td></tr></table></body></html>' }
function submissions(includeNonRevenue=true) { const values=rows.map(([, , , , , suffix,date])=>({accessionNumber:'0001046179-26-'+suffix,filingDate:date,form:'6-K',primaryDocument:'tsm-revenue'+date.replaceAll('-','')+'.htm'})); if(includeNonRevenue) values.push({accessionNumber:'0001046179-26-999999',filingDate:'2026-07-20',form:'6-K',primaryDocument:'tsm-earnings.htm'}); return {cik:1046179,name:'Taiwan Semiconductor Manufacturing Company Limited',tickers:['TSM'],filings:{recent:Object.fromEntries(['accessionNumber','filingDate','form','primaryDocument'].map((field)=>[field,values.map((value)=>value[field])]))}} }
function response(body,type,url,status=200) { return { status, url, headers: new Headers({'content-type':type}), json: async()=>JSON.parse(body), arrayBuffer: async()=>Buffer.from(body) } }
function fetcher({malformed=false}={}) { const metadata=submissions(); return async (url)=>{ if(url===TSMC_SEC_ACQUISITION.submissionsUrl) return response(JSON.stringify(metadata),'application/json',url); const filing=discoverTsmcMonthlyFilings(metadata).find((item)=>item.filingUrl===url); if(!filing) throw new Error('unexpected URL '+url); const row=rows.find((item)=>filing.filingDate===item[6]); let html=document(...row.slice(0,5)); if(malformed&&row[0]==='June') html=html.replace('TSMC June 2026 Revenue Report','TSMC Quarterly Update'); return response(html,'text/html; charset=utf-8',url) } }
async function root(){return mkdtemp(path.join(os.tmpdir(),'tsm-sec-test-'))}
const expected=rows.flatMap(([month,year,revenue,,yoy])=>{const period=year+'-'+String([...rows].findIndex((item)=>item[0]===month)+1).padStart(2,'0');return [[period,'MONTHLY_REVENUE',Number(revenue.replaceAll(',','')),'NT$ millions'],[period,'MONTHLY_REVENUE_YOY_PERCENT',Number(yoy),'percent']]})

test('SEC discovery deterministically selects revenue 6-K filings only',()=>{ const found=discoverTsmcMonthlyFilings(submissions()); assert.equal(found.length,6); assert.ok(found.every((item)=>item.form==='6-K'&&item.primaryDocument.startsWith('tsm-revenue')&&item.filingUrl.includes(item.accessionNumber.replaceAll('-','')))) })
test('SEC discovery accepts exact live TSMC identity and rejects incorrect CIK or ticker', () => { const live = { ...submissions(), name: 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' }; assert.equal(discoverTsmcMonthlyFilings(live).length, 6); assert.throws(() => discoverTsmcMonthlyFilings({ ...live, cik: 1 }), (error) => error.code === 'DISCOVERY_ISSUER'); assert.throws(() => discoverTsmcMonthlyFilings({ ...live, tickers: ['WRONG'] }), (error) => error.code === 'DISCOVERY_ISSUER') })
test('SEC filing ingestion preserves provenance and matches Jan-Jun golden baseline',async()=>{ const result=await ingestTsmcMonthlyFromSec({outputRoot:await root(),retrievedAt:'2026-08-14T00:00:00.000Z',fetchImpl:fetcher(),secUserAgent:agent,reportingYear:2026,acquisitionMode:'FIXTURE'}); const actual=result.document.records.map(({observation})=>[observation.period,observation.metric,observation.value,observation.unit]); assert.deepEqual(actual,expected); assert.equal(result.snapshots.length,6); for(const snapshot of result.snapshots){assert.equal(snapshot.provenance.cik,'0001046179');assert.equal(snapshot.provenance.formType,'6-K');assert.equal(snapshot.provenance.issuer,'TSMC');assert.equal(snapshot.provenance.evidenceDocument,'ISSUER_FILED_FORM_6_K');assert.equal(snapshot.provenance.filedWith,'SEC EDGAR');assert.equal(snapshot.provenance.acquisitionChannel,'SEC_EDGAR');assert.match(snapshot.provenance.accessionNumber,/^0001046179-26-/);assert.equal(snapshot.provenance.secFilingUrl,snapshot.evidenceUrl);assert.match(snapshot.sha256,/^[a-f0-9]{64}$/);assert.ok(snapshot.rawContentPath)} })
test('repeated accession ingestion is idempotent with stable observation IDs',async()=>{ const outputRoot=await root(); const first=await ingestTsmcMonthlyFromSec({outputRoot,retrievedAt:'2026-08-14T00:00:00.000Z',fetchImpl:fetcher(),secUserAgent:agent,reportingYear:2026,acquisitionMode:'FIXTURE'}); const second=await ingestTsmcMonthlyFromSec({outputRoot,retrievedAt:'2030-01-01T00:00:00.000Z',fetchImpl:fetcher(),secUserAgent:agent,reportingYear:2026,acquisitionMode:'FIXTURE'}); assert.equal(second.created,0);assert.equal(second.revisions,0);assert.deepEqual(second.document.records.map((record)=>record.observation.id),first.document.records.map((record)=>record.observation.id)) })
test('malformed revenue filing fails closed before promotion',async()=>{ const outputRoot=await root(); await assert.rejects(()=>ingestTsmcMonthlyFromSec({outputRoot,retrievedAt:'2026-08-14T00:00:00.000Z',fetchImpl:fetcher({malformed:true}),secUserAgent:agent,reportingYear:2026,acquisitionMode:'FIXTURE'}),(error)=>error instanceof IngestionError&&error.code==='NOT_MONTHLY_REVENUE') })
test('non-revenue 6-K content is rejected even with eligible-looking metadata',()=>{ const filing=discoverTsmcMonthlyFilings(submissions(false))[0]; const url=filing.filingUrl; const snapshot={httpStatus:200,contentType:'text/html',finalUrl:url,retrievedAt:'2026-08-14T00:00:00.000Z',snapshotId:'test',provenance:{cik:'0001046179',formType:'6-K',issuer:'TSMC',secFilingUrl:url,filingDate:filing.filingDate,accessionNumber:filing.accessionNumber,primaryDocument:filing.primaryDocument}}; assert.throws(()=>parseSecMonthlyRevenue(snapshot,'<html><body>FORM 6-K Taiwan Semiconductor Manufacturing Company Limited quarterly results</body></html>'),(error)=>error instanceof IngestionError&&error.code==='NOT_MONTHLY_REVENUE') })
test('SEC discovery unavailability fails closed',async()=>{ await assert.rejects(()=>ingestTsmcMonthlyFromSec({outputRoot:root(),fetchImpl:async()=>{throw new Error('offline')},secUserAgent:agent}),(error)=>error instanceof IngestionError&&error.code==='DISCOVERY_UNAVAILABLE') })
