import path from 'node:path'
import { IngestionError } from './shared/ingestion-error.mjs'
import { sha256, persistRawSnapshot } from './shared/snapshot-store.mjs'
import { promoteCanonicalAtomically } from './shared/canonical-store.mjs'
import { buildSecArchiveUrl, validateSecUserAgent } from './shared/sec-client.mjs'
import { matchesSecIssuerIdentity } from './shared/sec-issuer-identity.mjs'
import { requestWithRetry } from './shared/http-client.mjs'

export const AMZN_PPE_SOURCE=Object.freeze({id:'amzn-2026-q1-results',issuer:'AMZN',ticker:'AMZN',tier:'TIER_1_OFFICIAL',definitionId:'amzn-purchases-of-property-and-equipment',unit:'USD billions'})
export const AMZN_SEC_ACQUISITION=Object.freeze({cik:'0001018724',submissionsUrl:'https://data.sec.gov/submissions/CIK0001018724.json',archivesHostname:'www.sec.gov',formType:'10-Q',channel:'SEC_EDGAR'})
function fail(code,message,details={}){throw new IngestionError(code,message,details)}
function agent(value){return validateSecUserAgent(value)}
function filingUrl(filing){if(!/^amzn-\d{8}\.htm$/i.test(filing.primaryDocument))fail('PRIMARY_DOCUMENT','Invalid Amazon primary document');return buildSecArchiveUrl({cik:AMZN_SEC_ACQUISITION.cik,accessionNumber:filing.accessionNumber,primaryDocument:filing.primaryDocument})}
function eligible(filing){return filing.form==='10-Q'&&/^amzn-\d{8}\.htm$/i.test(filing.primaryDocument)}
export function discoverAmznQuarterlyFilings(submissions){if(!matchesSecIssuerIdentity(submissions,{cik:AMZN_SEC_ACQUISITION.cik,ticker:'AMZN',legalName:'Amazon.com, Inc.'}))fail('DISCOVERY_ISSUER','SEC submissions response is not Amazon');const recent=submissions?.filings?.recent;const fields=['accessionNumber','filingDate','reportDate','form','primaryDocument'];if(!recent||fields.some((field)=>!Array.isArray(recent[field])))fail('DISCOVERY_SCHEMA','SEC recent-filings metadata is incomplete');const count=recent.accessionNumber.length;if(fields.some((field)=>recent[field].length!==count))fail('DISCOVERY_SCHEMA','SEC recent-filings arrays are inconsistent');const found=[];for(let index=0;index<count;index++){const filing=Object.fromEntries(fields.map((field)=>[field,recent[field][index]]));if(eligible(filing))found.push({...filing,filingUrl:filingUrl(filing)})}if(new Set(found.map((item)=>item.accessionNumber)).size!==found.length)fail('DUPLICATE_ACCESSION','Duplicate SEC accession');return found.sort((a,b)=>b.reportDate.localeCompare(a.reportDate)||b.accessionNumber.localeCompare(a.accessionNumber))}
async function request(fetchImpl,url,options,code,signal,transport={},httpErrorCode=code){const collected=await requestWithRetry({...transport,url,options,errorCode:code,httpErrorCode,fetchImpl,signal});return{status:collected.response.status,url:collected.finalUrl,headers:collected.response.headers,arrayBuffer:async()=>collected.body,json:async()=>JSON.parse(collected.body.toString('utf8')),attempts:collected.attempts}}
export async function discoverFromSec({fetchImpl=fetch,secUserAgent,signal,transport={}}){const response=await request(fetchImpl,AMZN_SEC_ACQUISITION.submissionsUrl,{headers:{'user-agent':agent(secUserAgent??process.env.SEC_USER_AGENT),accept:'application/json'},redirect:'follow'},'DISCOVERY_UNAVAILABLE',signal,transport);if(response.status!==200)fail('DISCOVERY_UNAVAILABLE','SEC submissions returned '+response.status);if(!(response.headers.get('content-type')??'').toLowerCase().includes('json'))fail('DISCOVERY_CONTENT_TYPE','SEC submissions did not return JSON');let body;try{body=await response.json()}catch{fail('DISCOVERY_JSON','SEC submissions response is malformed JSON')}return discoverAmznQuarterlyFilings(body)}
function snapshotEvidenceUrl(snapshot){return snapshot.acquisitionMode==='FIXTURE'?snapshot.evidenceUrl:snapshot.finalUrl}
function text(value){return value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/&nbsp;|&#160;/gi,' ').replace(/&#58;/gi,':').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function parseCashValue(raw){const normalized=raw.replace(/[,$()\s]/g,'');if(!/^\d+$/.test(normalized))fail('MALFORMED_NUMBER','Malformed PP&E purchases value: '+raw);return Number(normalized)}
function quarterForMonth(month){if(month===3)return 1;if(month===6)return 2;if(month===9)return 3;fail('INCOMPLETE_TTM_PERIOD','Quarterly filing period is not a completed Amazon quarter')}
function parsedRows(table){return [...table.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map((row)=>[...row[1].matchAll(/<t[dh]\b([^>]*)>([\s\S]*?)<\/t[dh]>/gi)].map((cell)=>({value:text(cell[2]),colspan:Number(cell[1].match(/colspan\s*=\s*["']?(\d+)/i)?.[1]??1)})))}
function normalizedHeader(value){return value.replace(/,\s*$/,'').replace(/\s+/g,' ').trim()}
export function parseAmznPpePurchases(snapshot,html,source=AMZN_PPE_SOURCE){
  if(source.definitionId!==AMZN_PPE_SOURCE.definitionId)fail('INCOMPATIBLE_DEFINITION','Only purchases of property and equipment may enter this pipeline')
  const p=snapshot.provenance
  if(snapshot.httpStatus!==200||!snapshot.contentType.toLowerCase().includes('html'))fail('FILING_RESPONSE','SEC filing response is not HTML 200')
  if(!p||p.cik!==AMZN_SEC_ACQUISITION.cik||p.formType!=='10-Q'||p.issuer!=='Amazon'||p.definitionId!==source.definitionId)fail('FILING_PROVENANCE','Amazon filing provenance is inconsistent')
  if(snapshotEvidenceUrl(snapshot)!==p.secFilingUrl||new URL(snapshotEvidenceUrl(snapshot)).hostname!==AMZN_SEC_ACQUISITION.archivesHostname)fail('FILING_PROVENANCE','SEC archive URL is inconsistent')
  const all=text(html)
  if(!/FORM 10-Q/i.test(all)||!/AMAZON\.COM, INC\./i.test(all))fail('WRONG_ISSUER','Filing is not an Amazon Form 10-Q')
  const ended=all.match(/quarterly period ended\s+(March|June|September)\s+(\d{1,2}),\s+(20\d{2})/i)
  if(!ended)fail('INCOMPLETE_TTM_PERIOD','Quarterly reporting period is missing')
  if(!/Consolidated Statements of Cash Flows/i.test(all)||!/(?:\(|\b)in millions(?:\)|\b)/i.test(all))fail('AMBIGUOUS_UNITS','Cash-flow units are not unambiguously millions')
  const monthName=ended[1],month={March:3,June:6,September:9}[monthName[0].toUpperCase()+monthName.slice(1).toLowerCase()],year=Number(ended[3]),quarter=quarterForMonth(month),prior=year-1
  if(p.reportDate!==year+'-'+String(month).padStart(2,'0')+'-'+String(Number(ended[2])).padStart(2,'0'))fail('FILING_PROVENANCE','Report date conflicts with filing metadata')
  const matches=[]
  for(const table of [...html.matchAll(/<table\b[^>]*>[\s\S]*?<\/table>/gi)].map((match)=>match[0])){const rows=parsedRows(table);for(const row of rows)if(row.some((cell)=>cell.value==='Purchases of property and equipment'))matches.push({table,rows,row})}
  if(matches.length===0)fail('MISSING_PPE_ROW','Purchases of property and equipment row is missing')
  if(matches.length!==1)fail('DUPLICATE_PPE_ROW','Purchases of property and equipment row is duplicated')
  const {rows,row}=matches[0], target='Twelve Months Ended '+monthName+' '+ended[2]
  const expectedGroups=quarter===1?['Three Months Ended '+monthName+' '+ended[2],target]:quarter===2?['Three Months Ended '+monthName+' '+ended[2],'Six Months Ended '+monthName+' '+ended[2],target]:['Three Months Ended '+monthName+' '+ended[2],'Nine Months Ended '+monthName+' '+ended[2],target]
  const semanticGroups=(cells)=>cells.map((cell)=>normalizedHeader(cell.value)).filter((value)=>/^(?:Three|Six|Nine|Twelve) Months Ended /.test(value))
  const groupRows=rows.filter((cells)=>{const groups=semanticGroups(cells);return groups.length>0&&groups.join('|')===expectedGroups.join('|')})
  if(groupRows.length!==1)fail('INCOMPLETE_TTM_PERIOD','Expected one unambiguous ordered period-group header')
  const expectedYears=expectedGroups.flatMap(()=>[String(prior),String(year)]), yearRows=rows.filter((cells)=>{const years=cells.map((cell)=>cell.value).filter((value)=>/^20\d{2}$/.test(value));return years.join('|')===expectedYears.join('|')})
  if(yearRows.length!==1)fail('INCOMPLETE_TTM_PERIOD','Expected one unambiguous ordered year header')
  const labelIndex=row.findIndex((cell)=>cell.value==='Purchases of property and equipment'), financialCells=row.slice(labelIndex+1).filter((cell)=>cell.value!==''&&cell.value!=='$')
  if(financialCells.length!==expectedYears.length)fail('INCOMPLETE_TTM_PERIOD','PP&E row does not contain exactly one value per logical period')
  const values=financialCells.map((cell)=>({raw:cell.value,value:parseCashValue(cell.value)})), ttmOffset=(expectedGroups.length-1)*2
  const priorRaw=values[ttmOffset].raw, currentRaw=values[ttmOffset+1].raw
  const locator={accessionNumber:p.accessionNumber,primaryDocument:p.primaryDocument,statement:'Consolidated Statements of Cash Flows',row:'Purchases of property and equipment',reportedUnit:'USD millions',columns:['Twelve Months Ended '+monthName+' '+prior,'Twelve Months Ended '+monthName+' '+year]}
  const common={issuer:source.issuer,companyTicker:source.ticker,candidateType:'NUMERIC_METRIC',metric:'CAPEX_ACTUAL',unit:source.unit,periodType:'POINT_IN_TIME',capexDefinitionId:source.definitionId,sourceId:source.id,sourceUrl:snapshotEvidenceUrl(snapshot),publishedAt:p.filingDate+'T00:00:00.000Z',retrievedAt:snapshot.retrievedAt,snapshotId:snapshot.snapshotId,sourceDocumentVersionId:p.accessionNumber,sourceLocator:locator}
  return [{...common,period:'TTM-'+prior+'-Q'+quarter,value:parseCashValue(priorRaw)/1000,originalText:priorRaw},{...common,period:'TTM-'+year+'-Q'+quarter,value:parseCashValue(currentRaw)/1000,originalText:currentRaw}]
}
export function validateAmznPpeCandidates(candidates,snapshot,source=AMZN_PPE_SOURCE){if(!Array.isArray(candidates)||candidates.length!==2)fail('VALIDATION_FAILED','Expected exactly two Amazon TTM candidates');const keys=new Set();for(const item of candidates){if(item.companyTicker!=='AMZN'||item.metric!=='CAPEX_ACTUAL'||item.periodType!=='POINT_IN_TIME'||item.unit!=='USD billions'||item.capexDefinitionId!==source.definitionId||item.sourceId!==source.id||item.sourceUrl!==snapshotEvidenceUrl(snapshot)||item.snapshotId!==snapshot.snapshotId)fail('VALIDATION_FAILED','Amazon candidate contract mismatch');if(!/^TTM-20\d{2}-Q[1-3]$/.test(item.period)||typeof item.value!=='number'||!Number.isFinite(item.value)||item.value<=0)fail('VALIDATION_FAILED','Amazon candidate value or period is invalid');const key=[item.companyTicker,item.metric,item.period,item.unit,item.capexDefinitionId,item.sourceId].join('|');if(keys.has(key))fail('DUPLICATE_SEMANTIC_OBSERVATION','Duplicate Amazon semantic observation');keys.add(key)}if(Number(candidates[1].period.slice(4,8))-Number(candidates[0].period.slice(4,8))!==1||candidates[0].period.slice(-2)!==candidates[1].period.slice(-2))fail('INCOMPLETE_TTM_PERIOD','Amazon TTM comparison periods are incompatible');return candidates}
function logicalKey(item){return [item.companyTicker,item.metric,item.periodType,item.period,item.unit,item.sourceId,item.capexDefinitionId].join('|')}
// Explicit legacy adapter preserves production IDs; new pipelines use canonicalObservationId.
function legacyObservationId(item){const tsmKey=[item.companyTicker,item.metric,item.periodType,item.period,item.unit+'|'+item.capexDefinitionId,item.sourceId].join('|');return 'metric-observation:sha256:'+sha256(tsmKey+'|'+String(item.value))}
function observation(item,id){return{id,companyTicker:item.companyTicker,metric:item.metric,value:item.value,unit:item.unit,period:item.period,periodType:item.periodType,capexDefinitionId:item.capexDefinitionId,publishedAt:item.publishedAt,retrievedAt:item.retrievedAt,sourceId:item.sourceId,sourceUrl:item.sourceUrl}}
async function promoteCanonical({candidates,snapshot,canonicalPath}){return promoteCanonicalAtomically({candidates,snapshotIds:[snapshot.snapshotId],canonicalPath,pipelineId:'amzn-ppe-purchases',issuer:'AMZN',sourceId:AMZN_PPE_SOURCE.id,logicalFactKey:logicalKey,observationId:legacyObservationId,toObservation:observation,envelope:{capexDefinitionId:AMZN_PPE_SOURCE.definitionId}})}
async function collect({filing,outputRoot,retrievedAt,fetchImpl,secUserAgent,source,acquisitionMode,fixturePath,signal,transport}){const expected=filingUrl(filing);if(filing.filingUrl!==expected)fail('FILING_PROVENANCE','Filing URL is inconsistent');const response=await request(fetchImpl,expected,{headers:{'user-agent':agent(secUserAgent??process.env.SEC_USER_AGENT),accept:'text/html,application/xhtml+xml'},redirect:'follow'},'SOURCE_UNAVAILABLE',signal,transport,'FILING_RESPONSE');const finalUrl=response.url||expected;if(finalUrl!==expected||new URL(finalUrl).hostname!==AMZN_SEC_ACQUISITION.archivesHostname)fail('FILING_PROVENANCE','Filing did not resolve to immutable SEC URL');return persistRawSnapshot({body:Buffer.from(await response.arrayBuffer()),source,requestedUrl:expected,finalUrl,retrievedAt,status:response.status,contentType:response.headers.get('content-type')??'',outputRoot,acquisitionMode,acquisitionChannel:AMZN_SEC_ACQUISITION.channel,fixturePath:acquisitionMode==='FIXTURE'?fixturePath:undefined,fixtureId:acquisitionMode==='FIXTURE'?filing.accessionNumber:undefined,evidenceUrl:expected,provenance:{cik:AMZN_SEC_ACQUISITION.cik,accessionNumber:filing.accessionNumber,formType:filing.form,filingDate:filing.filingDate,reportDate:filing.reportDate,primaryDocument:filing.primaryDocument,secFilingUrl:expected,issuer:'Amazon',evidenceDocument:'AMAZON_ISSUER_FILED_FORM_10_Q',filedWith:'SEC EDGAR',acquisitionChannel:AMZN_SEC_ACQUISITION.channel,definitionId:source.definitionId}})}
export async function ingestAmznPpe({outputRoot,retrievedAt=new Date().toISOString(),fetchImpl=fetch,secUserAgent,reportPeriod,source=AMZN_PPE_SOURCE,acquisitionMode='LIVE',fixturePath='tests/fixtures/ingestion/amzn/2026-q1-10q-ppe.html',signal,transport={}}){const filings=await discoverFromSec({fetchImpl,secUserAgent,signal,transport});const filing=reportPeriod?filings.find((item)=>{const [year,quarter]=reportPeriod.split('-Q').map(Number);return item.reportDate.startsWith(String(year)+'-'+String(quarter*3).padStart(2,'0'))}):filings[0];if(!filing)fail('NO_ELIGIBLE_FILING','No Amazon 10-Q matched the requested period');const persisted=await collect({filing,outputRoot,retrievedAt,fetchImpl,secUserAgent,source,acquisitionMode,fixturePath,signal,transport});const candidates=parseAmznPpePurchases(persisted.snapshot,persisted.body,source);validateAmznPpeCandidates(candidates,persisted.snapshot,source);const canonicalPath=path.join(outputRoot,'observations','amzn-ppe-purchases.json');const promotion=await promoteCanonical({candidates,snapshot:persisted.snapshot,canonicalPath});return{filing,snapshot:persisted.snapshot,candidateCount:candidates.length,canonicalPath,...promotion}}
